// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ml_accel_ml_accel,hls_ip_2025_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.434000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=189,HLS_SYN_LUT=498,HLS_VERSION=2025_1}" *)

module ml_accel (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] radar_features_q0;
wire   [7:0] risk_level;
reg    risk_level_ap_vld;
wire   [7:0] confidence;
reg    confidence_ap_vld;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln42_fu_141_p2;
reg   [0:0] icmp_ln42_reg_308;
wire   [0:0] icmp_ln47_fu_147_p2;
reg   [0:0] icmp_ln47_reg_313;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln42_1_fu_175_p2;
reg   [0:0] icmp_ln42_1_reg_323;
wire   [0:0] icmp_ln47_1_fu_181_p2;
reg   [0:0] icmp_ln47_1_reg_328;
wire    ap_CS_fsm_state4;
wire   [0:0] and_ln42_fu_187_p2;
reg   [0:0] and_ln42_reg_338;
wire   [0:0] risk_fu_191_p2;
reg   [0:0] risk_reg_345;
wire   [0:0] icmp_ln58_fu_195_p2;
reg   [0:0] icmp_ln58_reg_351;
wire   [0:0] icmp_ln60_fu_201_p2;
reg   [0:0] icmp_ln60_reg_356;
wire    ap_CS_fsm_state5;
reg    radar_features_ce0_local;
reg   [1:0] radar_features_address0_local;
wire   [0:0] tmp_fu_153_p3;
wire   [15:0] sub_ln33_fu_161_p2;
wire   [15:0] velocity_1_fu_167_p3;
wire   [1:0] zext_ln47_fu_207_p1;
wire   [1:0] risk_1_fu_210_p3;
wire   [0:0] empty_fu_229_p2;
wire   [6:0] conf_fu_222_p3;
wire   [6:0] conf_1_fu_233_p3;
wire   [6:0] add_ln61_fu_247_p2;
wire   [6:0] conf_2_fu_241_p2;
wire   [6:0] conf_4_fu_253_p3;
wire   [15:0] add_ln64_fu_267_p2;
wire   [6:0] conf_3_fu_260_p3;
wire   [0:0] icmp_ln64_fu_273_p2;
wire   [6:0] add_ln64_1_fu_279_p2;
wire   [6:0] select_ln64_fu_285_p3;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

ml_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .radar_features_address0(radar_features_address0_local),
    .radar_features_ce0(radar_features_ce0_local),
    .radar_features_q0(radar_features_q0),
    .risk_level(risk_level),
    .risk_level_ap_vld(risk_level_ap_vld),
    .confidence(confidence),
    .confidence_ap_vld(confidence_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        and_ln42_reg_338 <= and_ln42_fu_187_p2;
        icmp_ln58_reg_351 <= icmp_ln58_fu_195_p2;
        icmp_ln60_reg_356 <= icmp_ln60_fu_201_p2;
        risk_reg_345 <= risk_fu_191_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln42_1_reg_323 <= icmp_ln42_1_fu_175_p2;
        icmp_ln47_1_reg_328 <= icmp_ln47_1_fu_181_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln42_reg_308 <= icmp_ln42_fu_141_p2;
        icmp_ln47_reg_313 <= icmp_ln47_fu_147_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        confidence_ap_vld = 1'b1;
    end else begin
        confidence_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        radar_features_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        radar_features_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        radar_features_address0_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        radar_features_address0_local = 64'd0;
    end else begin
        radar_features_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        radar_features_ce0_local = 1'b1;
    end else begin
        radar_features_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        risk_level_ap_vld = 1'b1;
    end else begin
        risk_level_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln61_fu_247_p2 = ($signed(conf_1_fu_233_p3) + $signed(7'd118));

assign add_ln64_1_fu_279_p2 = ($signed(conf_3_fu_260_p3) + $signed(7'd118));

assign add_ln64_fu_267_p2 = ($signed(radar_features_q0) + $signed(16'd65486));

assign and_ln42_fu_187_p2 = (icmp_ln42_reg_308 & icmp_ln42_1_reg_323);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conf_1_fu_233_p3 = ((empty_fu_229_p2[0:0] == 1'b1) ? conf_fu_222_p3 : 7'd40);

assign conf_2_fu_241_p2 = (conf_1_fu_233_p3 + 7'd10);

assign conf_3_fu_260_p3 = ((icmp_ln58_reg_351[0:0] == 1'b1) ? conf_2_fu_241_p2 : conf_4_fu_253_p3);

assign conf_4_fu_253_p3 = ((icmp_ln60_reg_356[0:0] == 1'b1) ? add_ln61_fu_247_p2 : conf_1_fu_233_p3);

assign conf_fu_222_p3 = ((and_ln42_reg_338[0:0] == 1'b1) ? 7'd85 : 7'd70);

assign confidence = select_ln64_fu_285_p3;

assign empty_fu_229_p2 = (risk_reg_345 | and_ln42_reg_338);

assign icmp_ln42_1_fu_175_p2 = (($signed(velocity_1_fu_167_p3) < $signed(16'd200)) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_141_p2 = (($signed(radar_features_q0) < $signed(16'd1000)) ? 1'b1 : 1'b0);

assign icmp_ln47_1_fu_181_p2 = (($signed(velocity_1_fu_167_p3) > $signed(16'd199)) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_147_p2 = (($signed(radar_features_q0) < $signed(16'd1500)) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_195_p2 = (($signed(radar_features_q0) > $signed(16'd300)) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_201_p2 = (($signed(radar_features_q0) < $signed(16'd150)) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_273_p2 = ((add_ln64_fu_267_p2 > 16'd200) ? 1'b1 : 1'b0);

assign risk_1_fu_210_p3 = ((and_ln42_reg_338[0:0] == 1'b1) ? 2'd2 : zext_ln47_fu_207_p1);

assign risk_fu_191_p2 = (icmp_ln47_reg_313 & icmp_ln47_1_reg_328);

assign risk_level = risk_1_fu_210_p3;

assign select_ln64_fu_285_p3 = ((icmp_ln64_fu_273_p2[0:0] == 1'b1) ? add_ln64_1_fu_279_p2 : conf_3_fu_260_p3);

assign sub_ln33_fu_161_p2 = (16'd0 - radar_features_q0);

assign tmp_fu_153_p3 = radar_features_q0[32'd15];

assign velocity_1_fu_167_p3 = ((tmp_fu_153_p3[0:0] == 1'b1) ? sub_ln33_fu_161_p2 : radar_features_q0);

assign zext_ln47_fu_207_p1 = risk_reg_345;

endmodule //ml_accel