// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="proximity_warning_and_control,hls_ip_2018_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.618000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=81,HLS_SYN_LUT=432,HLS_VERSION=2018_3}" *)

module proximity_warning_and_control (
        ap_clk,
        ap_rst,
        hall_rpm,
        object_distance,
        dashboard_alert,
        buzzer,
        pwm_duty
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input  [31:0] hall_rpm;
input  [31:0] object_distance;
output  [31:0] dashboard_alert;
output  [31:0] buzzer;
output  [31:0] pwm_duty;

reg[31:0] dashboard_alert;
reg[31:0] buzzer;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_1_fu_114_p2;
reg   [0:0] tmp_1_reg_195;
wire   [0:0] tmp_2_fu_120_p2;
reg   [0:0] tmp_2_reg_199;
wire   [0:0] grp_fu_107_p2;
reg   [0:0] tmp_5_reg_204;
wire   [0:0] tmp_4_fu_155_p2;
reg   [0:0] tmp_4_reg_209;
wire    ap_CS_fsm_state2;
wire   [0:0] or_cond_fu_166_p2;
reg   [0:0] or_cond_reg_214;
reg   [0:0] tmp_s_reg_218;
reg   [6:0] ap_phi_mux_storemerge1_phi_fu_97_p6;
reg   [6:0] storemerge1_reg_93;
wire    ap_CS_fsm_state4;
wire   [6:0] p_cast_fu_175_p3;
wire    ap_CS_fsm_state3;
reg   [31:0] grp_fu_107_p1;
wire   [31:0] object_distance_to_i_fu_126_p1;
wire   [7:0] tmp_fu_129_p4;
wire   [22:0] tmp_3_fu_139_p1;
wire   [0:0] notrhs_fu_149_p2;
wire   [0:0] notlhs_fu_143_p2;
wire   [0:0] tmp_6_fu_161_p2;
wire   [0:0] tmp_7_fu_171_p2;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

proximity_warning_and_control_fcmp_32ns_32ns_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
proximity_warning_and_control_fcmp_32ns_32ns_1_1_1_U1(
    .din0(object_distance),
    .din1(grp_fu_107_p1),
    .opcode(5'd2),
    .dout(grp_fu_107_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_reg_214 == 1'd0) & (tmp_1_reg_195 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                storemerge1_reg_93[2 : 1] <= p_cast_fu_175_p3[2 : 1];
        storemerge1_reg_93[6 : 4] <= p_cast_fu_175_p3[6 : 4];
    end else if (((1'b1 == ap_CS_fsm_state4) | ((or_cond_fu_166_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
                storemerge1_reg_93[1] <= 1'b0;
        storemerge1_reg_93[2] <= 1'b1;
        storemerge1_reg_93[4] <= 1'b0;
        storemerge1_reg_93[5] <= 1'b1;
        storemerge1_reg_93[6] <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        or_cond_reg_214 <= or_cond_fu_166_p2;
        tmp_4_reg_209 <= tmp_4_fu_155_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_1_reg_195 <= tmp_1_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_fu_114_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_2_reg_199 <= tmp_2_fu_120_p2;
        tmp_5_reg_204 <= grp_fu_107_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_166_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_s_reg_218 <= grp_fu_107_p2;
    end
end

always @ (*) begin
    if (((or_cond_reg_214 == 1'd0) & (tmp_1_reg_195 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_phi_mux_storemerge1_phi_fu_97_p6 = p_cast_fu_175_p3;
    end else begin
        ap_phi_mux_storemerge1_phi_fu_97_p6 = storemerge1_reg_93;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        buzzer = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state1))) begin
        buzzer = 32'd0;
    end else begin
        buzzer = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        dashboard_alert = 32'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        dashboard_alert = 32'd0;
    end else begin
        dashboard_alert = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_107_p1 = 32'd1092616192;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_107_p1 = 32'd1106247680;
    end else begin
        grp_fu_107_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((tmp_1_fu_114_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign notlhs_fu_143_p2 = ((tmp_fu_129_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_149_p2 = ((tmp_3_fu_139_p1 == 23'd0) ? 1'b1 : 1'b0);

assign object_distance_to_i_fu_126_p1 = object_distance;

assign or_cond_fu_166_p2 = (tmp_6_fu_161_p2 | tmp_2_reg_199);

assign p_cast_fu_175_p3 = ((tmp_7_fu_171_p2[0:0] === 1'b1) ? 7'd50 : 7'd20);

assign pwm_duty = ap_phi_mux_storemerge1_phi_fu_97_p6;

assign tmp_1_fu_114_p2 = ((hall_rpm == 32'd0) ? 1'b1 : 1'b0);

assign tmp_2_fu_120_p2 = (($signed(hall_rpm) < $signed(32'd121)) ? 1'b1 : 1'b0);

assign tmp_3_fu_139_p1 = object_distance_to_i_fu_126_p1[22:0];

assign tmp_4_fu_155_p2 = (notrhs_fu_149_p2 | notlhs_fu_143_p2);

assign tmp_6_fu_161_p2 = (tmp_5_reg_204 & tmp_4_fu_155_p2);

assign tmp_7_fu_171_p2 = (tmp_s_reg_218 & tmp_4_reg_209);

assign tmp_fu_129_p4 = {{object_distance_to_i_fu_126_p1[30:23]}};

always @ (posedge ap_clk) begin
    storemerge1_reg_93[0] <= 1'b0;
    storemerge1_reg_93[3] <= 1'b0;
end

endmodule //proximity_warning_and_control
