// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="classify_object,hls_ip_2018_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.560000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=468,HLS_SYN_LUT=1497,HLS_VERSION=2018_3}" *)

module classify_object (
        ap_clk,
        ap_rst_n,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] range_r;
wire   [31:0] velocity;
wire   [31:0] snr;
wire   [31:0] azimuth;
wire   [7:0] ap_return;
wire   [0:0] tmp_5_fu_130_p2;
reg   [0:0] tmp_5_reg_295;
wire   [0:0] tmp_s_fu_172_p2;
reg   [0:0] tmp_s_reg_303;
wire   [0:0] tmp_11_fu_178_p2;
reg   [0:0] tmp_11_reg_309;
wire   [0:0] notlhs3_fu_202_p2;
reg   [0:0] notlhs3_reg_315;
wire   [0:0] notrhs3_fu_208_p2;
reg   [0:0] notrhs3_reg_320;
wire   [0:0] tmp_15_fu_88_p2;
reg   [0:0] tmp_15_reg_325;
wire   [31:0] range_to_int_fu_94_p1;
wire   [7:0] tmp_1_fu_98_p4;
wire   [22:0] tmp_2_fu_108_p1;
wire   [0:0] notrhs_fu_118_p2;
wire   [0:0] notlhs_fu_112_p2;
wire   [0:0] tmp_3_fu_124_p2;
wire   [0:0] tmp_4_fu_70_p2;
wire   [31:0] velocity_to_int_fu_136_p1;
wire   [7:0] tmp_6_fu_140_p4;
wire   [22:0] tmp_7_fu_150_p1;
wire   [0:0] notrhs1_fu_160_p2;
wire   [0:0] notlhs1_fu_154_p2;
wire   [0:0] tmp_8_fu_166_p2;
wire   [0:0] tmp_9_fu_76_p2;
wire   [0:0] tmp_10_fu_82_p2;
wire   [31:0] snr_to_int_fu_184_p1;
wire   [7:0] tmp_12_fu_188_p4;
wire   [22:0] tmp_13_fu_198_p1;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_14_fu_214_p2;
wire   [0:0] sel_tmp4_fu_223_p2;
wire   [0:0] tmp_16_fu_218_p2;
wire   [0:0] tmp_fu_233_p2;
wire   [0:0] sel_tmp_fu_243_p2;
wire   [0:0] sel_tmp1_fu_248_p2;
wire   [0:0] sel_tmp8_fu_238_p2;
wire   [0:0] sel_tmp5_fu_228_p2;
wire   [0:0] or_cond_fu_257_p2;
wire   [1:0] newSel_cast_fu_253_p1;
wire   [1:0] newSel_fu_263_p3;
wire   [0:0] or_cond1_fu_279_p2;
wire   [1:0] newSel1_fu_271_p3;
wire   [1:0] newSel2_fu_283_p3;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

classify_object_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
classify_object_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(ap_return),
    .range_r(range_r),
    .velocity(velocity),
    .snr(snr),
    .azimuth(azimuth)
);

classify_object_fcmp_32ns_32ns_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
classify_object_fcmp_32ns_32ns_1_1_1_U1(
    .din0(range_r),
    .din1(32'd1097859072),
    .opcode(5'd4),
    .dout(tmp_4_fu_70_p2)
);

classify_object_fcmp_32ns_32ns_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
classify_object_fcmp_32ns_32ns_1_1_1_U2(
    .din0(velocity),
    .din1(32'd1069547520),
    .opcode(5'd4),
    .dout(tmp_9_fu_76_p2)
);

classify_object_fcmp_32ns_32ns_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
classify_object_fcmp_32ns_32ns_1_1_1_U3(
    .din0(velocity),
    .din1(32'd1073741824),
    .opcode(5'd2),
    .dout(tmp_10_fu_82_p2)
);

classify_object_fcmp_32ns_32ns_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
classify_object_fcmp_32ns_32ns_1_1_1_U4(
    .din0(snr),
    .din1(32'd1090519040),
    .opcode(5'd4),
    .dout(tmp_15_fu_88_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        notlhs3_reg_315 <= notlhs3_fu_202_p2;
        notrhs3_reg_320 <= notrhs3_fu_208_p2;
        tmp_11_reg_309 <= tmp_11_fu_178_p2;
        tmp_15_reg_325 <= tmp_15_fu_88_p2;
        tmp_5_reg_295 <= tmp_5_fu_130_p2;
        tmp_s_reg_303 <= tmp_s_fu_172_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return = newSel2_fu_283_p3;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign newSel1_fu_271_p3 = ((or_cond_fu_257_p2[0:0] === 1'b1) ? newSel_cast_fu_253_p1 : newSel_fu_263_p3);

assign newSel2_fu_283_p3 = ((or_cond1_fu_279_p2[0:0] === 1'b1) ? newSel1_fu_271_p3 : 2'd0);

assign newSel_cast_fu_253_p1 = sel_tmp1_fu_248_p2;

assign newSel_fu_263_p3 = ((sel_tmp5_fu_228_p2[0:0] === 1'b1) ? 2'd1 : 2'd2);

assign notlhs1_fu_154_p2 = ((tmp_6_fu_140_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs3_fu_202_p2 = ((tmp_12_fu_188_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs_fu_112_p2 = ((tmp_1_fu_98_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs1_fu_160_p2 = ((tmp_7_fu_150_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs3_fu_208_p2 = ((tmp_13_fu_198_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_118_p2 = ((tmp_2_fu_108_p1 == 23'd0) ? 1'b1 : 1'b0);

assign or_cond1_fu_279_p2 = (tmp_5_reg_295 | tmp_11_reg_309);

assign or_cond_fu_257_p2 = (sel_tmp8_fu_238_p2 | sel_tmp1_fu_248_p2);

assign range_to_int_fu_94_p1 = range_r;

assign sel_tmp1_fu_248_p2 = (tmp_11_reg_309 & sel_tmp_fu_243_p2);

assign sel_tmp4_fu_223_p2 = (tmp_s_reg_303 ^ 1'd1);

assign sel_tmp5_fu_228_p2 = (tmp_5_reg_295 & sel_tmp4_fu_223_p2);

assign sel_tmp8_fu_238_p2 = (tmp_fu_233_p2 & tmp_5_reg_295);

assign sel_tmp_fu_243_p2 = (tmp_5_reg_295 ^ 1'd1);

assign snr_to_int_fu_184_p1 = snr;

assign tmp_11_fu_178_p2 = (tmp_8_fu_166_p2 & tmp_10_fu_82_p2);

assign tmp_12_fu_188_p4 = {{snr_to_int_fu_184_p1[30:23]}};

assign tmp_13_fu_198_p1 = snr_to_int_fu_184_p1[22:0];

assign tmp_14_fu_214_p2 = (notrhs3_reg_320 | notlhs3_reg_315);

assign tmp_16_fu_218_p2 = (tmp_15_reg_325 & tmp_14_fu_214_p2);

assign tmp_1_fu_98_p4 = {{range_to_int_fu_94_p1[30:23]}};

assign tmp_2_fu_108_p1 = range_to_int_fu_94_p1[22:0];

assign tmp_3_fu_124_p2 = (notrhs_fu_118_p2 | notlhs_fu_112_p2);

assign tmp_5_fu_130_p2 = (tmp_4_fu_70_p2 & tmp_3_fu_124_p2);

assign tmp_6_fu_140_p4 = {{velocity_to_int_fu_136_p1[30:23]}};

assign tmp_7_fu_150_p1 = velocity_to_int_fu_136_p1[22:0];

assign tmp_8_fu_166_p2 = (notrhs1_fu_160_p2 | notlhs1_fu_154_p2);

assign tmp_fu_233_p2 = (tmp_s_reg_303 & tmp_16_fu_218_p2);

assign tmp_s_fu_172_p2 = (tmp_9_fu_76_p2 & tmp_8_fu_166_p2);

assign velocity_to_int_fu_136_p1 = velocity;

endmodule //classify_object
